#! /bin/sh

nvidia-settings --load-config-only &
nitrogen --restore &
picom &
sxhkd &
$HOME/.config/polybar/launch.sh

bspc wm -O HDMI-0 DP-0
bspc monitor HDMI-0 -d 1 2 3 4 5 
bspc monitor DP-0 -d 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a TelegramDesktop -o state=floating rectangle=750x560+1100+400
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
